nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web

web:
  build: ./web
  links:
    - mongodb
  ports:
    - "5000:5000"
  command: /usr/bin/python /app/app.py
  restart: always
  volumes:
    - ./web:/app
  env_file: .env

mongodb:
  restart: always
  build: ./mongo
  volumes:
    - data:/data
  ports:
    - "27017:27017"
