web:
  build: ./web
  links:
    - mongodb
  ports:
    - "5000:5000"
  command: /usr/bin/python /app/app.py
  restart: always

mongodb:
  restart: always
  build: ./mongo
  volumes:
    - data:/data
  ports:
    - "27017:27017"
